# Generated by Django 5.1.5 on 2025-01-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_jobs_owner_jobs_booked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='booked_by',
        ),
        migrations.DeleteModel(
            name='Owners',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
