# Generated by Django 5.1.5 on 2025-01-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='owner',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
