# Generated by Django 5.1.5 on 2025-01-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
