# Generated by Django 5.1.5 on 2025-01-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_usermodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
